<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Welcome to your professional communi_3ca9dc</name>
   <tag></tag>
   <elementGuidId>a9671f58-78ac-4dc7-b68f-d9c7375f7457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='gsi_890375_303769']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gsi_890375_303769</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8d56f725-f8f9-48c4-8b94-78e100248f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://accounts.google.com/gsi/button?logo_alignment=center&amp;shape=pill&amp;size=large&amp;text=continue_with&amp;theme=undefined&amp;type=undefined&amp;width=398&amp;client_id=990339570472-k6nqn1tpmitg8pui82bfaun3jrpmiuhs.apps.googleusercontent.com&amp;iframe_id=gsi_890375_303769&amp;as=dCiu3B4lvKBcSimMkfrQoQ&amp;hl=en_US</value>
      <webElementGuid>7dfa24a6-9c45-4fa8-9f45-dda1a086d14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gsi_890375_303769</value>
      <webElementGuid>eb4062ec-23d0-4f46-9e65-e7be553828c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sign in with Google Button</value>
      <webElementGuid>35a2b43b-02c4-4ee6-8ec2-0488a2c939c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gsi_890375_303769&quot;)</value>
      <webElementGuid>c73428a0-25c8-460e-b122-c7a45cfc6eef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='gsi_890375_303769']</value>
      <webElementGuid>26874bd8-49f6-4b62-b6de-3fbb06f6b329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main-content']/section/div/div/div/div/div/iframe</value>
      <webElementGuid>00ab8b31-94fd-44dd-8fba-089fb72f9c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>cdff84d7-8994-44e6-bc67-82a3f081ca63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://accounts.google.com/gsi/button?logo_alignment=center&amp;shape=pill&amp;size=large&amp;text=continue_with&amp;theme=undefined&amp;type=undefined&amp;width=398&amp;client_id=990339570472-k6nqn1tpmitg8pui82bfaun3jrpmiuhs.apps.googleusercontent.com&amp;iframe_id=gsi_890375_303769&amp;as=dCiu3B4lvKBcSimMkfrQoQ&amp;hl=en_US' and @id = 'gsi_890375_303769' and @title = 'Sign in with Google Button']</value>
      <webElementGuid>abc8da36-d8c6-4fad-adeb-72f33629990d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
